# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1d77ffb1-47b3-4494-b3dc-398f40b111ca";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B2A-3DEA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/immich" =
    { device = "/dev/disk/by-uuid/a0f5d20d-f870-457f-8502-952ff44c3cb3";
      fsType = "btrfs";
      options = [ "subvol=immich" ];
    };

  fileSystems."/data/.snapshots" =
    { device = "/dev/disk/by-uuid/a0f5d20d-f870-457f-8502-952ff44c3cb3";
      fsType = "btrfs";
      options = [ "subvol=snapshots" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
