wallpaper {
    monitor = DP-3
    path = /home/dod/Pictures/wallpapers/sleep1.png
}

wallpaper {
    monitor = DP-2
    path = /home/dod/Pictures/wallpapers/sleep2.png
}

wallpaper {
    monitor = DP-1
    path = /home/dod/Pictures/wallpapers/sleep3.png
}

wallpaper {
    monitor = HDMI-A-3
    path = /home/dod/Pictures/wallpapers/sleep2.png
}

splash = false